title: Noah Harman
description: Mechanical & Aerospace Engineer
site_title: 'Noah Harman Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: nrh46
email: nrh46@cornell.edu

# absolute or relative
profile_picture: assets/images/pp.jpg